version: "3.7"

services:
  rabbit:
    image: rabbitmq:3.9.5-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5672:5672"
      - "15672:15672"